// Generated by CoffeeScript 1.5.0
(function() {
  var User, dsn, mongoose, populateUsers;

  mongoose = require('mongoose');

  User = require('../models/User').User;

  dsn = "mongodb://localhost/rental";

  mongoose.connect(dsn, function(err) {
    if (err) {
      throw err;
    }
  });

  populateUsers = function() {
    var peggyData, peggyUser;
    console.log("In populateUsers");
    peggyData = {
      name: {
        first: "Peggy",
        last: "D"
      },
      email: "oz.basarir@gmail.com",
      password: "urla",
      salt: "ABAEBCDCBE"
    };
    peggyUser = new User(peggyData);
    console.log(peggyUser);
    return peggyUser.save(function(err, item) {
      console.log("In save function");
      if (err) {
        return console.log(err);
      } else {
        return console.log(item);
      }
    });
  };

  populateUsers();

}).call(this);
