// Generated by CoffeeScript 1.5.0
(function() {
  var Owner, dsn, mongoose, populateOwners;

  mongoose = require('mongoose');

  Owner = require('../models/Owner').Owner;

  dsn = "mongodb://localhost/rental";

  mongoose.connect(dsn, function(err) {
    if (err) {
      throw err;
    }
  });

  populateOwners = function() {
    var peggyData, peggyOwner;
    console.log("In populateOwners");
    peggyData = {
      name: {
        first: "Peggy",
        last: "D"
      },
      email: "oz.basarir@gmail.com",
      password: "urla",
      salt: "ABAEBCDCBE"
    };
    peggyOwner = new Owner(peggyData);
    console.log(peggyOwner);
    return peggyOwner.save(function(err, item) {
      console.log("In save function");
      if (err) {
        return console.log(err);
      } else {
        return console.log(item);
      }
    });
  };

  populateOwners();

}).call(this);
