// Generated by CoffeeScript 1.5.0
(function() {
  var Property, dsn, mongoose, populatePropertys;

  mongoose = require('mongoose');

  Property = require('../models/Property').Property;

  dsn = "mongodb://localhost/rental";

  mongoose.connect(dsn, function(err) {
    if (err) {
      throw err;
    }
  });

  populateProperties = function() {
    var studioData, studioProperty;
    console.log("In populateProperties");
    studioData = {
      name: "studio"
    };
    studioProperty = new Property(studioData);
    console.log(studioProperty);
    return studioProperty.save(function(err, item) {
      console.log("In save function");
      if (err) {
        return console.log(err);
      } else {
        return console.log(item);
      }
    });
  };

  populateProperties();

}).call(this);
