// Generated by CoffeeScript 1.5.0
(function() {
  var Rental, dsn, mongoose, populateRentals;

  mongoose = require('mongoose');

  Rental = require('../models/Rental').Rental;

  dsn = "mongodb://localhost/rental";

  mongoose.connect(dsn, function(err) {
    if (err) {
      throw err;
    }
  });

  populateRentals = function() {
    var studioData, studioRental;
    console.log("In populateRentals");
    studioData = {
      name: "studio"
    };
    studioRental = new Rental(studioData);
    console.log(studioRental);
    return studioRental.save(function(err, item) {
      console.log("In save function");
      if (err) {
        return console.log(err);
      } else {
        return console.log(item);
      }
    });
  };

  populateRentals();

}).call(this);
