// Generated by CoffeeScript 1.5.0
(function() {
  var OwnerSchema, mongoose, validatePresenceOf;

  mongoose = require("../node_modules/mongoose");

  validatePresenceOf = function(value) {
    return value && value.length;
  };

  OwnerSchema = new mongoose.Schema({
    name: {
        first: String
      , last : String
    },
    email: {
      type: String,
      required: true,
      lowercase: true,
      validate: [validatePresenceOf, 'an email is required'],
      index: {
        unique: true,
        sparse: true
      }
    },
    password: String,
    salt: String,
    created_on: {
      type: Date,
      "default": Date.now
    },
    third_party_id: {
      type: String,
      index: {
        unique: true,
        sparse: true
      }      
    }
  });

  exports.Owner = mongoose.model('Owner', OwnerSchema, 'owner');

}).call(this);
//Add an eTag or ModifiedDate?