// Generated by CoffeeScript 1.5.0
// Look in node_modules/mongoose/examples/schema.js for examples
(function() {
  var PropertySchema, mongoose, Owner, validatePresenceOf, enumRateType, enumCurrencyType;

  mongoose = require("../node_modules/mongoose");
  Owner = require('./Owner').Owner;

  validatePresenceOf = function(value) {
    return value && value.length;
  };

  enumRateType = ['Nightly', 'Weekly'];
  enumCurrencyType = ['dollar', 'euro'];
  PropertySchema = new mongoose.Schema({
    name: {
      type: String,
//      validate: [validatePresenceOf, 'a name is required'],
//      index: {
//        unique: true
//      }
    },
    slug: { type: String, lowercase: true, trim: true },
    owner: { type: mongoose.Schema.Types.ObjectId, ref: Owner},
    rates: [{
      type:       { type: String, enum: enumRateType },
      startDate:  { type: Date },
      endDate:    { type: Date },
      currency:   { type: String, enum: enumCurrencyType },
      amount:     { type: Number }
    }],
    created_on: { type: Date, "default": Date.now }
  });

  /**
   * Plugins
   */

  function slugGenerator (options){
    options = options || {};
    var key = options.key || 'name';

    return function slugGenerator(schema){
      schema.path(key).set(function(v){
        this.slug = v.toLowerCase().replace(/[^a-z0-9]/g, '').replace(/-+/g, '');
        return v;
      });
    };
  };

  PropertySchema.plugin(slugGenerator());


  exports.Property = mongoose.model('Property', PropertySchema, 'property');

}).call(this);
